# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adf67406d00817d31723957797e4bf61fa6180ed46f708b0391e90d0c00143398c7ceca4c9e0fbaf7c69096809e04674c490bcfd4052541e88da19c44551c356

test:
  secret_key_base: fff11bc971115796a5d17b9b4a98b43e9590ae9d7988845bf26562394b8a89346303c7b0e91670e27296284b2de725b1f97e5fb3e33a48af39c6adc1dc143a2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
